### ISSUE TITLE
Possibility to filter tasks

### ISSUE THREAD

**Issue by juho-jaakkola** [sbwtech/elgg-projects#13]
For example:
 - Status (open, closed, reopened, etc)
 - Assignee (own tab for "Assigned to me"?)

**Comment by michelesbw** [comment]
Nice but I wouldn't add stuff until users won't ask them :)

**Comment by juho-jaakkola** [comment]
I started working on these filters but then realized it isn't possible to make a database query simultaneously both with metadata (task status) and relationships (assignees).

![image](https://user-images.githubusercontent.com/883920/34115996-6c8ff4fc-e417-11e7-81ea-464ab22909a7.png)

AFAIK Elgg 3 will support such use case, but I'm not sure how to make the filters work in Elgg 2.

**Comment by michelesbw** [comment]
Thanks for trying but no problems. It's a nice feature but not required at the moment so we can leave it behind ;)

**Comment by juho-jaakkola** [comment]
I made an ugly hack and the filters works.
