### ISSUE TITLE
Fatal error when trying to access a task not available for the user

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/elgg-projects#14]
Fatal error: Call to a member function getContainerEntity() on boolean in /var/www/vhosts/beta.socialbusinessworld.org/httpdocs/mod/projects/views/default/resources/task/view.php on line 8

**Comment by juho-jaakkola** [comment]
Happens when trying to access any task that hasn't been made visible for the user (regardless if user is logged in or not).

**Comment by michelesbw** [comment]
Huh? Please don't change titles so easily :D. The link was received by a user to whom a task was assigned (notification) so the user should not only view but also "manage" that task (ie. mark it as complete), am I wrong?

**Comment by juho-jaakkola** [comment]
Was the user logged in to Elgg when they clicked on the link in the email?

**Comment by juho-jaakkola** [comment]
I'll take that as a yes. :smile:

**Comment by michelesbw** [comment]
It was a like on you closing this issue :D
