### ISSUE TITLE
when start date is on one day end end date on the next day, it shows only 1 day in the calendar

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/elgg-projects#15]
As reported by user

**Comment by juho-jaakkola** [comment]
`Day 1, 00:00 AM` - `Day 2, 00:00 AM` = `24h` = `1 day`

Not sure what to do about this. Perhaps the end date should instead automatically save the time as "The entered date + 24h", so it would become two days.

**Comment by juho-jaakkola** [comment]
But this would show the wrong date in the task info (one day too much). So perhaps it should be "entered date + 23h, 59min". But even this would cause trouble when the reporter and the assignee are in different time zones.

**Comment by juho-jaakkola** [comment]
Or perhaps the date in the database could remain the same, but one extra day would be added for the data before it is passed to the calendar view.

**Comment by michelesbw** [comment]
Maybe the best way (dunno if easy) would be adding start/end time in 24 hours format so that it should be more precise. So... Start Date, Start time, End Date, End Time
