### ISSUE TITLE
Icon for Menu

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/elgg-projects#16]
https://fontawesome.com/icons/tasks?style=solid

**Comment by juho-jaakkola** [comment]
The icon is slightly different in Font awesome version 4 than it is in that preview page which uses version 5.

**Comment by juho-jaakkola** [comment]
Fixed in https://github.com/sbwtech/theme_sbw/commit/504d9b499ab8e07c87fcef7cd16cd9d3b7bb67de

**Comment by michelesbw** [comment]
Yes, I know the icon is different, version 4 is not nice in my opinion, is it a probem to use that V5?

**Comment by juho-jaakkola** [comment]
Version 4 is bundled in Elgg 2.

**Comment by michelesbw** [comment]
I thought icons could also be downloaded/uploaded, sorry. Hopefully Elgg 3 will include V5, much nicer and of course fresher :)
