### ISSUE TITLE
In Tasks view each task should also show status (open/completed),assignees, start/end/actual end dates

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/elgg-projects#17]

**Comment by juho-jaakkola** [comment]
Aren't assignees and the dates already visible?

**Comment by michelesbw** [comment]
They mean ie here https://beta.socialbusinessworld.org/project/view/787021?tab=tasks

**Comment by juho-jaakkola** [comment]
This should really be solved with filters instead.

**Comment by michelesbw** [comment]
I don't fully agree. Info is not that much for each Task so having them at a glance without further filtering/clicking/selecting is a better UX in my opinion

**Comment by juho-jaakkola** [comment]
The task listing page now has both filters, and the status of each task:

![image](https://user-images.githubusercontent.com/883920/34775160-74463a78-f612-11e7-841e-5e29fe9a7926.png)

**Comment by michelesbw** [comment]
Great!

**Comment by michelesbw** [comment]
I think it doesn't retrieve Assignees correctly. Check here, the list only has "Any Assignee" or "Juho Jaakkola" /project/view/787021?tab=tasks

**Comment by juho-jaakkola** [comment]
The filter lists only the people who are participating in the project. When new users are added, they become available in the filters.

**Comment by michelesbw** [comment]
I know but in that project there are tasks assigned also to other users which should be retrieved by filters, right?

**Comment by juho-jaakkola** [comment]
There was indeed a bug. Now the filter has all the options.
