### ISSUE TITLE
In calendar view, projects and tasks should also indicate if open/completed

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/elgg-projects#18]

**Comment by juho-jaakkola** [comment]
Any ideas on how this should be indicated?

**Comment by michelesbw** [comment]
Icon? Color? Label (this would be better, "Complete" or "To be completed"

**Comment by juho-jaakkola** [comment]
Color are better because they do not require space from the event box, and it's easier to see the overall status visually.

![image](https://user-images.githubusercontent.com/883920/34764221-14865aec-f5ee-11e7-959d-6aa9b90bf147.png)

**Comment by michelesbw** [comment]
Ok, nice for me but can we add some explanation for colors in the view? Above or below the tabs?

**Comment by juho-jaakkola** [comment]
How about these icons within the even box:
 - http://fontawesome.io/icon/check-circle-o/
 - http://fontawesome.io/icon/times-circle-o/

**Comment by michelesbw** [comment]
"check" is ok but "times" too close to cancel or delete concepts...not sure
