### ISSUE TITLE
More details into the project list page

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/elgg-projects#19]
- Status (open/completed)
- Number of open/completed tasks
- Start/end/actual end dates

**Comment by michelesbw** [comment]
As for view they mean ie here https://beta.socialbusinessworld.org/project/all

**Comment by juho-jaakkola** [comment]
Isn't it a bit too much do display *everything* on the listing page. It *is* after all the listing page, not the details page.

**Comment by juho-jaakkola** [comment]
Here's the current work:
![image](https://user-images.githubusercontent.com/883920/34767197-ccc2a42c-f5f7-11e7-9f54-b60fdbfffcce.png)

**Comment by juho-jaakkola** [comment]
What the page really needs is filters, not more visible details.

**Comment by michelesbw** [comment]
I reported what funders asked for. Filters can also be a valid solution but what you did also is nice so I would keep that work.

**Comment by juho-jaakkola** [comment]
The project listing page now has:
 - Open/Closed/All tabs
 - Number of closed/total tasks

![image](https://user-images.githubusercontent.com/883920/34944099-8abee8d2-f9fe-11e7-964f-0e728aa484d7.png)

IMO the rest of the information does not belong to the listing page. It becomes too cluttered.

**Comment by michelesbw** [comment]
I also like it.
IMO "Open" tab shoud be the default one (I see it as first tab but not sure if it's default one when opening "Projects" page) and it should also contain "1/5 completed" info like is now in "All" tab

**Comment by juho-jaakkola** [comment]
All other has been added except for the dates. Let's close for now, and collect user feedback.
