### ISSUE TITLE
Add related project's name to task lists

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/elgg-projects#3]
So that user easily see each task which project is related to

**Comment by juho-jaakkola** [comment]
This problem appears just in the widget, right? In all other task lists the project is known.

 I was thinking whether we should allow creating project specific widgets. So each widget would display only the tasks of a single project. The widget title would show the name of the project.

What do you think? Which is more useful:
 - One widget displaying all users tasks
 - Multiple displaying tasks of single projects

**Comment by michelesbw** [comment]
I would go with 1 widget only, yes the issue is in widget only
