### ISSUE TITLE
Allow creating personal projects (not within groups)

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/elgg-projects#6]

**Comment by juho-jaakkola** [comment]
What does this mean?

**Comment by michelesbw** [comment]
As in points 3 and 5 here /pages/view/874402/tasks-compiti

**Comment by juho-jaakkola** [comment]
So you mean it should be possible to have projects both within:
 - Groups (get listed on the page "Projects of the group X")
 - A specific user account (get listed on the page "Projects owned by user X") **<-- This one**

**Comment by michelesbw** [comment]
Yes, like discussions are now in Elgg 2 (sitewide discussions or group discussions)
