### ISSUE TITLE
Notifications to user on tasks assigned/removed to/for them

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/elgg-projects#8]
Which of these do we need?

## Personal notifications
- [x] Notification to assignee when task is assigned/removed

### A) Group notifications
Notifications will be sent to all group members who have enabled notifications **on the group level**.

- [x] Notification to all group members when any project is:
  - Created
  - Closed
- [ ] Notification to all group members when any tasks is:
  - Created
  - Reopened
  - Closed

### B) Project notifications
Notifications will be sent only from the projects where user has explicitly subscribed to them (as opposed to having subscribed to group notifications = all projects within the group).

- [x] Notification to all followers of a single project when task is:
  - Created
  - Reopened
  - Closed

**Comment by juho-jaakkola** [comment]
IMO the best option might be that notifications about **projects** would be handled on group level, and notifications of **tasks** on a project level.

So if you have enabled group notifications, you would receive a notifications when any projects is created/closed within the group. However you would receive notifications about the tasks only if you have explicitly chosen them from each project individually. E.g. receive notifications about tasks in projects A and B, but not from project C.

**Comment by michelesbw** [comment]
Totally agree
