### ISSUE TITLE
Reminders on tasks to assignees 

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/elgg-projects#9]
(ie. -1 month/week, -3 days,....) with relevant info. Notifications need to be on/off by users as all other notifications (SBW standard)

**Comment by juho-jaakkola** [comment]
I suppose these notifications will use the notification methods defined on the project level as defined in https://github.com/sbwtech/elgg-projects/issues/8#issuecomment-347028734?

**Comment by michelesbw** [comment]
As for users we meant "assignees" so the addition here is sending reminders at predefined intervals

**Comment by juho-jaakkola** [comment]
Any idea of what kind of UI would be good for enabling the notifications? Is is simple of/off option, or should the user be able to choose also the desired time/interval? Would the reminder be set on project or task level?

**Comment by michelesbw** [comment]
I would stick to initial spec: "Reminders on tasks to users (ie. -1 month/week, -3 days,....) with relevant info. Notifications need to be on/off by users as all other notifications (SBW standard)"
So, ON/OFF for each Project (for project owner) and Tasks (for assignees).
As for interval I think it's easier/better to have them set sitewide...maybe too complicated for users to manage each reminder for each task. What do you think?

**Comment by juho-jaakkola** [comment]
I personally wouldn't want to be forced to receive a message of every task every interval (-1m, -1w, -3d). Some tasks may not be relevant at all a month before their deadline.

But I'll do that for now, and think about more granular settings later.

**Comment by michelesbw** [comment]
Mines were only examples to make things clearer. I also think 1m is not relevant. I would set them at -10 days, -1week, -3 days, -1 day

**Comment by juho-jaakkola** [comment]
How do reminders work if task takes more than one day? Should reminder be sent e.g. 7 days before the task is supposed to be started or 7 days before the task is supposed to be completed?

**Comment by juho-jaakkola** [comment]
Which one is it reminding of?
 - A new task will be starting soon
 - A deadline of a task will be soon

**Comment by michelesbw** [comment]
I think reminding about deadines is enough
